version: "3.8"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orgdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: orgdb
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
volumes:
  mysql_data:
